excluded:
  - .build
  - vendor

disabled_rules:
  - line_length
  - weak_delegate

opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - private_outlet
  - sorted_imports

type_name:
  max_length: 60

cyclomatic_complexity:
  ignores_case_statements: true

identifier_name:
  min_length:
    error: 4
  max_length: 60
  excluded:
    - app
    - lhs
    - rhs
    - uk
  
file_length:
  warning: 500
  error: 800

line_length:
  ignores_urls: true
  ignores_comments: true
