# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# update_fastlane

default_platform(:ios)

before_all do
  setup_ci
end

platform :ios do
  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(type: "appstore")
    match(type: "development")
  end

  desc "Test"
  lane :test do
    scan
  end

  desc "Build"
  lane :build do
    match(type: "appstore")
    update_code_signing_settings(use_automatic_signing: false)
    gym(skip_archive: true)
    update_code_signing_settings(use_automatic_signing: true)
  end

  desc "Build and Sign"
  lane :build_and_sign do
    match(type: "appstore")
    update_code_signing_settings(use_automatic_signing: false)
    gym
    update_code_signing_settings(use_automatic_signing: true)
  end

  desc "Upload to TestFlight"
  lane :beta do
    ensure_git_branch(branch: "main")
    app_store_connect_api_key
    match(type: "appstore")
    increment_build_number(
      build_number: latest_testflight_build_number + 1,
    )
    update_code_signing_settings(use_automatic_signing: false)
    gym
    testflight
    update_code_signing_settings(use_automatic_signing: true)
  end

  desc "Submit to AppStore for Review"
  lane :submit_review do
    app_store_connect_api_key
    deliver
  end
end

platform :mac do
  desc "Fetches the provisioning profiles so you can build locally and deploy to your device"
  lane :certs do
    match(type: "appstore")
    match(type: "development")
  end

  desc "Test"
  lane :test do
    scan
  end

  desc "Build"
  lane :build do
    match(type: "appstore")
    gym
  end

  desc "Build and Sign"
  lane :build_and_sign do
    match(type: "appstore")
    update_code_signing_settings(use_automatic_signing: false)
    gym
    update_code_signing_settings(use_automatic_signing: true)
  end
end
